version: '3.7'

services:
    rocket_science_test.fpm:
        env_file: .env
        build:
            context: docker/php-fpm
            dockerfile: Dockerfile
            network: host
        working_dir: /var/www/project
        restart: unless-stopped
        volumes:
            - ./:/var/www/project

    rocket_science_test.nginx:
        image: nginx:latest
        env_file: .env
        restart: unless-stopped
        depends_on:
            - rocket_science_test.fpm
        ports:
            - ${DOCKER_NGINX_HTTP_PORT}:80
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled

    rocket_science_test.postgres:
        image: postgres:9.5-alpine
        container_name: rocket_science_test.postgres
        volumes:
            - "./docker/postgres:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=${DOCKER_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
            - POSTGRES_DB=${DOCKER_POSTGRES_DB}
        ports:
            - ${DOCKER_POSTGRES_PORT}:5432

